import { ConvexError, v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { requireProfile } from "./lib/auth";

const priority = v.union(v.literal("Low"), v.literal("Medium"), v.literal("High"));
const status = v.union(v.literal("Open"), v.literal("Completed"));
const taskValue = v.any();
const present = (x: any, lead?: any, assignee?: any) => ({ ...x, id: x._id, dueAt: x.dueAt ? new Date(x.dueAt).toISOString() : null, createdAt: new Date(x._creationTime).toISOString(), updatedAt: new Date(x.updatedAt).toISOString(), lead: lead ? { ...lead, id: lead._id } : null, assignee: assignee ? { id: assignee._id, fullName: assignee.fullName, email: assignee.email } : null });
async function owned(ctx: any, id: any) { const p = await requireProfile(ctx); const row = await ctx.db.get(id); if (!row || row.workspaceId !== p.workspaceId) throw new ConvexError("Task not found."); return row; }

export const list = query({ args: {}, returns: v.array(taskValue), handler: async (ctx) => { const p = await requireProfile(ctx); const rows = await ctx.db.query("tasks").withIndex("by_workspace_id", (q) => q.eq("workspaceId", p.workspaceId)).collect(); const values = await Promise.all(rows.map(async (x) => present(x, x.leadId ? await ctx.db.get(x.leadId) : null, x.assignedToId ? await ctx.db.get(x.assignedToId) : null))); return values.sort((a, b) => (a.dueAt ?? "9999").localeCompare(b.dueAt ?? "9999")); } });
export const create = mutation({ args: { title: v.string(), leadId: v.optional(v.id("leads")), assignedToId: v.optional(v.id("profiles")), category: v.optional(v.string()), description: v.optional(v.string()), dueAt: v.optional(v.string()), priority: v.optional(priority), reminderEnabled: v.optional(v.boolean()) }, returns: taskValue, handler: async (ctx, args) => { const p = await requireProfile(ctx); if (!args.title.trim()) throw new ConvexError("Task title is required."); if (args.leadId) { const lead = await ctx.db.get(args.leadId); if (!lead || lead.workspaceId !== p.workspaceId) throw new ConvexError("Invalid lead."); } const id = await ctx.db.insert("tasks", { workspaceId: p.workspaceId, createdById: p._id, assignedToId: args.assignedToId ?? p._id, leadId: args.leadId, title: args.title.trim(), category: args.category ?? "Call", description: args.description, dueAt: args.dueAt ? Date.parse(args.dueAt) : undefined, priority: args.priority ?? "Medium", status: "Open", reminderEnabled: args.reminderEnabled ?? true, updatedAt: Date.now() }); return present((await ctx.db.get(id))!); } });
export const update = mutation({ args: { id: v.id("tasks"), changes: v.object({ title: v.optional(v.string()), leadId: v.optional(v.id("leads")), assignedToId: v.optional(v.id("profiles")), category: v.optional(v.string()), description: v.optional(v.string()), dueAt: v.optional(v.string()), priority: v.optional(priority), status: v.optional(status), reminderEnabled: v.optional(v.boolean()) }) }, returns: taskValue, handler: async (ctx, { id, changes }) => { await owned(ctx, id); const clean: any = Object.fromEntries(Object.entries(changes).filter(([, x]) => x !== undefined)); if (clean.dueAt) clean.dueAt = Date.parse(clean.dueAt); await ctx.db.patch(id, { ...clean, updatedAt: Date.now() }); return present((await ctx.db.get(id))!); } });
export const remove = mutation({ args: { id: v.id("tasks") }, returns: v.null(), handler: async (ctx, { id }) => { await owned(ctx, id); await ctx.db.delete(id); return null; } });
