import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Search } from "lucide-react";
import { leadService } from "../../services/leadService";

export default function AdvancedSearch() {
  const [leads, setLeads] = useState([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const navigate = useNavigate();
  useEffect(() => { leadService.getLeads().then((data) => setLeads(Array.isArray(data) ? data : [])).catch(console.error); }, []);
  const results = useMemo(() => leads.filter((lead) => `${lead.businessName} ${lead.email} ${lead.phone} ${lead.category}`.toLowerCase().includes(query.toLowerCase()) && (!status || lead.status === status)), [leads, query, status]);
  return <div><h1 className="crm-page-title text-xl">Advanced Search</h1><p className="mb-5 text-xs text-slate-500">Refine your pipeline with multiple criteria.</p><section className="crm-card p-5"><div className="grid gap-3 md:grid-cols-[1fr_180px_auto]"><div className="relative"><Search className="absolute left-3 top-2.5 text-[#0e8e86]" size={16}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by business name, phone, or email..." className="crm-input w-full py-2 pl-9 pr-3 text-sm"/></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="crm-input px-3 text-sm"><option value="">All statuses</option>{["New", "Hot", "Warm", "Cold", "Won", "Lost"].map((item) => <option key={item}>{item}</option>)}</select><button onClick={() => { setQuery(""); setStatus(""); }} className="rounded-md border border-slate-300 px-3 text-xs font-bold">Clear Filters</button></div></section><div className="mt-5 space-y-3">{results.map((lead) => <article key={lead.id} className="crm-card flex items-center justify-between p-4"><div><strong className="text-[#172b4d]">{lead.businessName}</strong><p className="mt-1 text-xs text-slate-500">{lead.category || "General"} · {lead.email || lead.phone || "No contact"}</p></div><div className="flex items-center gap-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{lead.status || "New"}</span><button onClick={() => navigate(`/leads/${lead.id}`)} className="rounded-md border border-[#162b55] px-3 py-1.5 text-xs font-bold text-[#172b4d]">View</button></div></article>)}{!results.length && <div className="crm-card p-8 text-center text-sm text-slate-500">No matching leads.</div>}</div></div>;
}
